"files": [
  {
    "source": "/content/**/*.md",
    "translation": "/localizedContent/%two_letters_code%/%original_path%/%original_file_name%",
    "ignore": [
      "/**/TOC.md"
    ],
    "translation_replace": {
      "content": ""
    }
  },
  {
    "source": "/content/404.html",
    "translation": "/localizedContent/%two_letters_code%/404.html"
  },
  {
    "source": "/content/toc.yml",
    "translation": "/localizedContent/%two_letters_code%/toc.yml"
  }
]
