"files": [
  {
    "source": "/content/**/*.md",
    "translation": "/localizedContent/%two_letters_code%/%original_path%/%original_file_name%",
    "ignore": [
      "/**/TOC.md"
    ],
    "translation_replace": {
      "/content/": "/"
    }
  }
]
