apiRules:
- exclude:
    uidRegex: ^TabularEditor\.Shared\.Services
    type: Namespace
- exclude:
    hasAttribute:
      uid: System.ComponentModel.EditorBrowsableAttribute
      ctorArguments:
      - System.ComponentModel.EditorBrowsableState.Never