#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Generate docfx configuration files and redirects.

This script:
1. Generates localizedContent/en/docfx.json for English with redirects
2. Scans localizedContent/ for language folders
3. Generates localizedContent/{lang}/docfx.json for each language

Note: languages.json manifest is generated by gen_languages.py (not this script).

Usage: python gen_redirects.py
"""

import copy
import json
import os
import sys
import traceback


def get_available_languages() -> list[str]:
    """Scan localizedContent/ folder and return list of language codes (excluding 'en')."""
    localized_dir = "localizedContent"
    if not os.path.exists(localized_dir):
        return []
    
    languages = []
    for item in os.listdir(localized_dir):
        item_path = os.path.join(localized_dir, item)
        # Exclude 'en' since it's generated, not stored
        if os.path.isdir(item_path) and len(item) <= 5 and item != "en":
            languages.append(item)
    
    return sorted(languages)


def generate_localized_config(template: dict, lang: str) -> dict:
    """Generate a docfx config for a specific language based on the template.
    
    Note: Config files are placed in localizedContent/{lang}/docfx.json alongside
    a content/ subdirectory. This allows ~/content/... paths in markdown to resolve
    correctly (~ = config location = localizedContent/{lang}/).
    
    Structure:
        localizedContent/{lang}/
            docfx.json          <- generated config
            content/
                features/       <- localized/fallback content
                assets/images/  <- shared resources
                ...
    """
    config = copy.deepcopy(template)
    
    # Remove metadata section (API generation) - localized sites use copied API docs
    if "metadata" in config:
        del config["metadata"]
    
    build = config["build"]
    
    # Since docfx.json is in localizedContent/{lang}/ and content is in 
    # localizedContent/{lang}/content/, paths stay the same as the English template
    # No path modifications needed for content entries!
    
    # Resource paths: keep local content/ paths, but for any fallback to main
    # content folder, we'd use ../../content/ (but we copy everything locally now)
    
    # Set output destination to language subfolder (relative to project root)
    # From localizedContent/{lang}/, we go up twice to reach project root
    build["dest"] = f"../../_site/{lang}"
    
    # Update template paths - need to go up two levels to reach project root
    if "template" in build:
        new_templates = []
        for t in build["template"]:
            if t == "default":
                new_templates.append(t)
            else:
                # templates/tabulareditor -> ../../templates/tabulareditor
                new_templates.append(f"../../{t}")
        build["template"] = new_templates
    
    return config


def generate_redirects_config(template: dict) -> dict:
    """Generate English docfx.json with corrected paths for the build layout.

    Fixes metadata, dest, and template paths which need to go up two levels
    relative to localizedContent/en/ to reach the project root.
    Client redirect HTML pages are generated separately by gen_staticwebapp_config.py.
    """
    config = copy.deepcopy(template)

    # Fix metadata paths (API generation) - need to go up two levels to reach project root
    # DocFX doesn't support ../ in file globs, so we use src to set the base directory
    if "metadata" in config:
        for meta in config["metadata"]:
            if "src" in meta:
                new_src = []
                for src in meta["src"]:
                    if "files" in src:
                        new_src.append({"src": "../..", "files": src["files"]})
                    else:
                        new_src.append(src)
                meta["src"] = new_src
            if "dest" in meta:
                meta["dest"] = f"../../{meta['dest']}"
            if "filter" in meta:
                meta["filter"] = f"../../{meta['filter']}"

    # Set English output destination (relative to localizedContent/en/)
    config["build"]["dest"] = "../../_site/en"

    # Update template paths - need to go up two levels to reach project root
    if "template" in config["build"]:
        new_templates = []
        for t in config["build"]["template"]:
            if t == "default":
                new_templates.append(t)
            else:
                new_templates.append(f"../../{t}")
        config["build"]["template"] = new_templates

    return config


def main(args: list[str]) -> int:
    config_input_path = "docfx-template.json"
    localized_content_dir = "localizedContent"
    
    # Load template
    with open(config_input_path) as f:
        template = json.load(f)
    
    # Create English directory
    en_dir = os.path.join(localized_content_dir, "en")
    en_content_dir = os.path.join(en_dir, "content")
    os.makedirs(en_content_dir, exist_ok=True)

    # Generate English config in localizedContent/en/
    # Note: client redirect HTML pages are generated by gen_staticwebapp_config.py
    en_config_path = os.path.join(en_dir, "docfx.json")
    print(f"Generating {en_config_path} (English)...")
    english_config = generate_redirects_config(template)
    with open(en_config_path, "w") as f:
        json.dump(english_config, f, indent=4)
    
    # Get available languages from localizedContent/ (excludes 'en')
    languages = get_available_languages()
    all_languages = ["en"] + languages
    print(f"Found {len(all_languages)} language(s): {', '.join(all_languages)}")
    
    # Generate config for each non-English language
    for lang in languages:
        lang_dir = os.path.join(localized_content_dir, lang)
        os.makedirs(lang_dir, exist_ok=True)
        
        config_path = os.path.join(lang_dir, "docfx.json")
        print(f"Generating {config_path}...")
        
        localized_config = generate_localized_config(template, lang)
        with open(config_path, "w") as f:
            json.dump(localized_config, f, indent=4)
    
    # Note: languages.json manifest is generated by gen_languages.py
    # which provides rich metadata (display names, native names, rtl, etc.)
    
    print("Done!")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main(sys.argv[1:]))
    except Exception as ex:
        traceback.print_exception(ex, file=sys.stderr)
        sys.exit(1)
